# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('num_reviews', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coordinates', models.CharField(max_length=50)),
                ('review_summary', models.TextField()),
                ('day_0', models.CharField(max_length=50, verbose_name='Sun')),
                ('day_1', models.CharField(max_length=50, verbose_name='Mon')),
                ('day_2', models.CharField(max_length=50, verbose_name='Tue')),
                ('day_3', models.CharField(max_length=50, verbose_name='Wed')),
                ('day_4', models.CharField(max_length=50, verbose_name='Thu')),
                ('day_5', models.CharField(max_length=50, verbose_name='Fri')),
                ('day_6', models.CharField(max_length=50, verbose_name='Sat')),
            ],
        ),
    ]
