# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20171226_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Attraction',
        ),
    ]
