# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20171226_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['country', 'score']},
        ),
    ]
