# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20171226_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='country',
            field=models.CharField(default='ABC', max_length=50),
            preserve_default=False,
        ),
    ]
