# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20171226_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='review_summary',
            field=models.TextField(max_length=5000),
        ),
    ]
